# Configure max HEAP size
USER_FLAGS+="-Wl,--defsym,__neorv32_heap_size=1024"

# Modify this variable to fit your NEORV32 setup (neorv32 home folder)
NEORV32_HOME ?= ../../..

include $(NEORV32_HOME)/sw/common/common.mk
