# Modify this variable to fit your NEORV32 setup (neorv32 home folder)
NEORV32_HOME ?= ../../../..
MARCH ?= rv32i_zicsr_zifencei_zfinx
NEORV32_SIM_FOLDER = $(NEORV32_SIM_PATH)/benchmark

include $(NEORV32_HOME)/sw/common/common.mk
