<<<
:sectnums:
==== Numerically-Controlled Oscillator (NCO)

[cols="<3,<3,<4"]
[frame="topbot",grid="none"]
|=======================
| Hardware source file(s): | neorv32_nco.vhd | 
| Software driver file(s): | neorv32_nco.c |
|                          | neorv32_nco.h |
| Top entity port:         | `nco_o` | NCO output (3x 1-bit channels)
| Configuration generics:  | _IO_NCO_EN_ | implement NCO when _true_
| CPU interrupts:          | none | 
|=======================

**Theory of Operation**

The numerically-controller oscillator (NCO) provides a precise arbitrary linear frequency generator with
three independent channels. Based on a **direct digital synthesis** core, the NCO features a 20-bit wide
accumulator that is incremented with a programmable "tuning word". Whenever the accumulator overflows, a
flip flop is toggled that provides the actual frequency output. The accumulator increment is driven by one of
eight configurable clock sources, which are derived from the processor's main clock.

The NCO features four accessible registers: the control register _NCO_CT_ and three _NCO_TUNE_CHi_ registers for
the tuning word of each channel i. The NCO is globally enabled by setting the _NCO_CT_EN_ bit in the control
register. If this bit is cleared, the accumulators of all channels are reset. The clock source for each channel i is
selected via the three bits _NCO_CT_CHi_PRSCx_ prescaler. The resulting clock is generated from the main
processor clock (f~main~) divided y the selected prescaler.

.NCO prescaler configuration
[cols="<4,^1,^1,^1,^1,^1,^1,^1,^1"]
[options="header",grid="rows"]
|=======================
| **`NCO_CT_CHi_PRSCx`**      | `0b000` | `0b001` | `0b010` | `0b011` | `0b100` | `0b101` | `0b110` | `0b111`
| Resulting `clock_prescaler` |       2 |       4 |       8 |      64 |     128 |    1024 |    2048 |    4096
|=======================

The resulting output frequency of each channel i is defined by the following equation:

_**f~NCO~(i)**_ = ( _f~main~[Hz]_ / `clock_prescaler`(i) ) * (`tuning_word`(i) / 2*2^20+1^)

The maximum NCO frequency f~NCOmax~ is configured when using the minimal clock prescaler and a maximum all-one
tuning word:

_**f~NCOmax~**_ = ( _f~main~[Hz]_ / 2 ) * (1 / 2*2^20+1^)

The minimum "frequency" is always 0 Hz when the tuning word is zero. The frequency resolution f~NCOres~ is
defined using the maximum clock prescaler and a minimal non-zero tuning word (= 1):

_**f~NCOres~**_ = ( _f~main~[Hz]_ / 4096 ) * (1 / 2*2^20+1^)

Assuming a processor frequency of f~main~ = 100 MHz the maximum NCO output frequency is f~NCOmax~ = 12.499
MHz with an NCO frequency resolution of f~NCOres~ = 0.00582 Hz.

**Advanced Configuration**

The idle polarity of each channel is configured via the _NCO_CT_CHi_IDLE_POL_ flag and can be either `0`
(idle low) or `1` (idle high), which basically allows to invert the NCO output. If the NCO is globally disabled
by clearing the _NCO_CT_EN_ flag, `nco_o(i)` output bit i is set to the according _NCO_CT_CHi_IDLE_POL_.

The current state of each NCO channel output can be read by software via the NCO_CT_CHi_OUTPUT bit.
The NCO frequency output is normally available via the top nco_o output signal. The according channel
output can be permanently set to zero by clearing the according NCO_CT_CHi_OE bit.

Each NCO channel can operate either in standard mode or in pulse mode. The mode is configured via the
according channel's NCO_CT_CHi_MODE control register bit.

**_Standard_ Operation Mode**

If this _NCO_CT_CHi_MODE_ bit of channel i is cleared, the channel operates in standard mode providing a
frequency with **exactly 50% duty cycle** (T~high~ = T~low~).

**_Pulse_ Operation Mode**

If the _NCO_CT_CHi_MODE_ bit of channel i is set, the channel operates in pulse mode. In this mode, the duty
cycle can be modified to generate active pulses with variable length. Note that the "active" pulse polarity is defined
by the inverted _NCO_CT_CHi_IDLE_POL_ bit.

Eight different pulse lengths are available. The active pulse length is defined as number of NCO clock
cycles, where the NCO clock is defined via the clock prescaler bits _NCO_CT_Chi_PRSCx_. The pulse length
of channel i is programmed by the 3-bit _NCO_CT_CHi_PULSEx_ configuration:

.NCO pulse length configuration
[cols="<4,^1,^1,^1,^1,^1,^1,^1,^1"]
[options="header",grid="rows"]
|=======================
| **`NCO_CT_CHi_PULSEx`**            | `0b000` | `0b001` | `0b010` | `0b011` | `0b100` | `0b101` | `0b110` | `0b111`
| Pulse length (in NCO clock cycles) |       2 |       4 |       8 |      16 |      32 |      64 |     128 |    256
|=======================

If _NCO_CT_CHi_IDLE_POL_ is cleared, T~high~ is defined by the _NCO_CT_CHi_PULSEx_ configuration and T~low~ =
T – T~high~. _If NCO_CT_CHi_IDLE_POL_ is set, T~low~ is defined by the _NCO_CT_CHi_PULSEx_ configuration and
T~high~ = T – T~low~.

The actual output frequency of the channel (defined via the clock prescaler and the tuning word) is not
affected by the pulse configuration.

For simple PWM applications, that do not require a precise frequency but a more flexible duty cycle
configuration, see section <<_pulse_width_modulation_controller_pwm>>.

<<<
.NCO register map
[cols="<4,<3,<9,^2,<11"]
[options="header",grid="all"]
|=======================
| Address | Name [C] | Bit(s), Name [C] | R/W | Function
.22+<| `0xffffffc0` .22+<| _NCO_CT_ ^|`0` _NCO_CT_EN_            ^| r/w <| NCO enable
                                  3+^| Channel 0 `nco_o(0)`
                                    ^|`1` _NCO_CT_CH0_MODE_      ^| r/w <| output mode (`0`=fixed 50% duty cycle; `1`=pulse mode)
                                    ^|`2` _NCO_CT_CH0_IDLE_POL_  ^| r/w <| output idle polarity
                                    ^|`3` _NCO_CT_CH0_OE_        ^| r/w <| enable output to `nco_o(0)`
                                    ^|`4` _NCO_CT_CH0_OUTPUT_    ^| r/- <| current state of `nco_o(0)`
                                    ^|`7:5` _NCO_CT_CH0_PRSC02_ : _NCO_CT_CH0_PRSC0_ ^| r/w <| 3-bit clock prescaler select
                                    ^|`10_:8` _NCO_CT_CH0_PULSE2_ : _NCO_CT_CH0_PULSE0_ ^| r/w <| 3-bit pulse length select
                                  3+^| Channel 1 `nco_o(1)`
                                    ^|`11` _NCO_CT_CH1_MODE_     ^| r/w <| output mode (`0`=fixed 50% duty cycle; `1`=pulse mode)
                                    ^|`12` _NCO_CT_CH1_IDLE_POL_ ^| r/w <| output idle polarity
                                    ^|`13` _NCO_CT_CH1_OE_       ^| r/w <| enable output to `nco_o(1)`
                                    ^|`14` _NCO_CT_CH1_OUTPUT_   ^| r/- <| current state of `nco_o(1)`
                                    ^|`17:15` _NCO_CT_CH1_PRSC2_ : _NCO_CT_CH1_PRSC0_ ^| r/w <| 3-bit clock prescaler select
                                    ^|`20:18` _NCO_CT_CH1_PULSE2_ : _NCO_CT_CH1_PULSE0_ ^| r/w <| 3-bit pulse length select
                                  3+^| Channel 2 `nco_o(2)`
                                    ^|`21` _NCO_CT_CH2_MODE_     ^| r/w <| output mode (`0`=fixed 50% duty cycle; `1`=pulse mode)
                                    ^|`22` _NCO_CT_CH2_IDLE_POL_ ^| r/w <| output idle polarity
                                    ^|`23` _NCO_CT_CH2_OE_       ^| r/w <| enable output to `nco_o(2)`
                                    ^|`24` _NCO_CT_CH2_OUTPUT_   ^| r/- <| current state of `nco_o(2)`
                                    ^|`27:25` _NCO_CT_CH2_PRSC2_ : _NCO_CT_CH2_PRSC0_ ^| r/w <| 3-bit clock prescaler select
                                    ^|`30:28` _NCO_CT_CH2_PULSE2_ : _NCO_CT_CH2_PULSE0_ ^| r/w <| 3-bit pulse length select
|=======================
