<<<
:sectnums:
==== Instruction Memory (IMEM)

[cols="<3,<3,<4"]
[frame="topbot",grid="none"]
|=======================
| Hardware source file(s): | neorv32_imem.vhd | 
| Software driver file(s): | none             | _implicitly used_
| Top entity port:         | none             | 
| Configuration generics:  | _MEM_INT_IMEM_EN_ | implement processor-internal IMEM when _true_
|                          | _MEM_INT_IMEM_SIZE_ | IMEM size in bytes
|                          | _MEM_INT_IMEM_ROM_ | implement IMEM as ROM when _true_
| CPU interrupts:          | none             | 
|=======================

Implementation of the processor-internal instruction memory is enabled via the processor's
_MEM_INT_IMEM_EN_ generic. The size in bytes is defined via the _MEM_INT_IMEM_SIZE_ generic. If the
IMEM is implemented, the memory is mapped into the instruction memory space and located right at the
beginning of the instruction memory space (default `ispace_base_c` = 0x00000000).

By default, the IMEM is implemented as RAM, so the content can be modified during run time. This is
required when using a bootloader that can update the content of the IMEM at any time. If you do not need
the bootloader anymore – since your application development has completed and you want the program to
permanently reside in the internal instruction memory – the IMEM can also be implemented as true _read-only_
memory. In this case set the _MEM_INT_IMEM_ROM_ generic of the processor's top entity to _true_.

When the IMEM is implemented as ROM, it will be initialized during synthesis with the actual application
program image. The compiler toolchain will generate a VHDL initialization
file `rtl/core/neorv32_application_image.vhd`, which is automatically inserted into the IMEM. If
the IMEM is implemented as RAM (default), the memory will **not be initialized** at all.
