<<<
:sectnums:
==== Bootloader ROM (BOOTROM)

[cols="<3,<3,<4"]
[frame="topbot",grid="none"]
|=======================
| Hardware source file(s): | neorv32_boot_rom.vhd | 
| Software driver file(s): | none             | _implicitly used_
| Top entity port:         | none             | 
| Configuration generics:  | _INT_BOOTLOADER_EN_ | implement processor-internal bootloader when _true_
| CPU interrupts:          | none             | 
|=======================

[NOTE]
The default `neorv32_boot_rom.vhd` HDL source file provides a _generic_ memory design that infers embedded
memory. You might need to replace/modify the source file in order to use platform-specific features
(like advanced memory resources) or to improve technology mapping and/or timing.

As the name already suggests, the processor-internal boot ROM contains the read-only bootloader image. When the bootloader
is enabled via the __INT_BOOTLOADER_EN__ generic it is directly executed after system reset.

The bootloader ROM is located at address 0xFFFF0000. This location is fixed and the bootloader ROM size
must not exceed 32kB. The bootloader read-only memory is automatically initialized during synthesis via the
`rtl/core/neorv32_bootloader_image.vhd` file, which is generated when compiling and installing the
bootloader sources.

The bootloader ROM address space cannot be used for other applications even when the bootloader is not
implemented.

.Boot Configuration
[TIP]
See section <<_boot_configuration>> for more information regarding the processor's different boot scenarios.

[TIP]
See section <<_bootloader>> for more information regarding the bootloader's boot process and configuration options.
