<<<
:sectnums:
==== Bootloader ROM (BOOTROM)

[cols="<3,<3,<4"]
[frame="topbot",grid="none"]
|=======================
| Hardware source file(s): | neorv32_boot_rom.vhd | 
| Software driver file(s): | none                 | 
| Top entity port:         | none                 | 
| Configuration generics:  | `INT_BOOTLOADER_EN`  | implement processor-internal bootloader when `true`
| CPU interrupts:          | none                 | 
|=======================

This boot ROM module provides a read-only memory that contain the executable image of the default NEORV32
<<_bootloader>>. If the internal bootloader is enabled via the `INT_BOOTLOADER_EN` generic the CPU's boot address
is automatically set to the beginning of the bootloader ROM. See section <<_boot_configuration>> for more
information regarding the processor's different boot scenarios.

.Address Configuration
[NOTE]
The bootloader ROM is located at address `0xFFFF0000` and can occupy an address space of up to 32kB. The base
address as well as the maximum address space size are fixed and cannot be modified as this might cause address
collision with other processor modules.

.Read-Only Access
[NOTE]
Any write access to the BOOTROM will raise a _store access fault_ exception.
