<<<
<<<
:sectnums:
==== Processor-Internal Data Cache (dCACHE)

[cols="<3,<3,<4"]
[grid="none"]
|=======================
| Hardware source files:  | neorv32_cache.vhd   | Generic cache module
| Software driver files:  | none                |
| Top entity ports:       | none                |
| Configuration generics: | `DCACHE_EN`         | implement processor-internal data cache when `true`
|                         | `DCACHE_NUM_BLOCKS` | number of cache blocks (pages or lines); has to be a power of two
|                         | `DCACHE_BLOCK_SIZE` | size of a cache block in bytes; has to be a power of two
| CPU interrupts:         | none |
|=======================


**Overview**

The processor features an optional data cache to improve performance when using memories with high
access latency. The cache is connected directly to the CPU's data access interface and provides
full-transparent accesses. The cache is direct-mapped and uses "write-allocate" and "write-back" strategies.

.Uncached Accesses
[NOTE]
The data cache provides direct accesses (= uncached) to memory in order to access memory-mapped IO (like the
processor-internal IO/peripheral modules). All accesses that target the address range from `0xF0000000` to `0xFFFFFFFF`
will not be cached at all (see section <<_address_space>>). Furthermore, the atomic memory operations
of the <<_zaamo_isa_extension>> will always **bypass** the cache.

.Manual Cache Flush/Clear/Reload and Memory Coherence
[NOTE]
By executing the `fence` instruction the data cache is flushed, cleared and reloaded.
See section <<_memory_coherence>> for more information.

.Retrieve Cache Configuration from Software
[TIP]
Software can retrieve the cache configuration/layout from the <<_sysinfo_cache_configuration>> register.

.Bus Access Fault Handling
[NOTE]
If the cache encounters a bus error when uploading a modified block to the next memory level or when
downloading a new block from the next memory level, the entire block is invalidated and a bus access
error exception is raised.
