<<<
:sectnums:
==== Data Memory (DMEM)

[cols="<3,<3,<4"]
[grid="none"]
|=======================
| Hardware source files:  | neorv32_dmem.vhd     | generic processor-internal data memory (RAM)
|                         | neorv32_dmem_ram.vhd | RAM component (primitive/IP wrapper)
| Software driver files:  | none                 |
| Top entity ports:       | none                 |
| Configuration generics: | `DMEM_EN`            | implement DMEM when `true`
|                         | `DMEM_SIZE`          | DMEM size in bytes (use a power of 2)
|                         | `DMEM_OUTREG_EN`     | add DMEM output register stage
| CPU interrupts:         | none                 |
|=======================

**Key Features**

* Burst-capable tightly-coupled on-chip data memory
* Configurable RAM size
* Accessible at the byte level
* Can also be used for executing code
* Mapped to memory primitives
* Optional output register for improved timing


**Overview**

Implementation of the processor-internal data memory is enabled by the processor's `DMEM_EN`
generic. The total memory size in bytes is defined via the `DMEM_SIZE` generic. Only sizes that
are powers of two are supported. If enabled, the DEME is mapped to base address `0x80000000`
(see section <<_address_space>>).

.Platform-Specific Memory Primitives
[NOTE]
If required, the default DMEM can be replaced by a platform-/technology-specific primitive to
optimize area utilization, timing and power consumption.

.Output Register Stage
[TIP]
An optional output register stage can be enabled via `DMEM_OUTREG_EN`. For FPGA targets this might improve
mapping/timing results. Note that this option will increase the read latency by one clock cycle. Write accesses
are not affected by this at all.

.Retrieve Memory Configuration by Software
[TIP]
Software can retrieve the DMEM size from the <<_sysinfo_miscellaneous_configuration>> register.

.Memory Primitives
[TIP]
The memory's memory core is encapsulated as individual wrapper (`neorv32_dmem_ram.vhd`) that can be
replaced by a technology-specific IP. All interface ports provide static signal widths to ease replacement.
