<<<
:sectnums:
==== Internal Bus Monitor (BUSKEEPER)

[cols="<3,<3,<4"]
[frame="topbot",grid="none"]
|=======================
| Hardware source file(s): | neorv32_buskeeper.vhd | 
| Software driver file(s): | none | 
| Top entity port:         | none | 
| Configuration generics:  | none | 
| Package constants:       | `max_proc_int_response_time_c` | Access time window (maximum number of cycles)
| CPU interrupts:          | none | 
|=======================


**Theory of Operation**

The Bus Keeper is a fundamental component of the processor's internal bus system that ensures correct operations
while maintaining execution safety. It operates transparently for the user by monitoring every single bus transactions
that is initiated by the CPU. If an accessed device responds with an error condition or does not respond at all within
a specific **access time window**, an according bus access fault exception is raised. The following exceptions can be
raised by the bus keeper:

* `TRAP_CODE_I_ACCESS`: error / timeout during instruction fetch bus access
* `TRAP_CODE_S_ACCESS`: error / timeout during data store bus access
* `TRAP_CODE_L_ACCESS`: error / timeout during data load bus access

.Access Time Window
[IMPORTANT]
The **access time window**, in which an accessed device has to respond, is defined by the `max_proc_int_response_time_c`
constant from the processor's VHDL package file (`rtl/neorv32_package.vhd`). The default value is **15 clock cycles**.

.Register Map
[NOTE]
The bus keeper does not provide any memory-mapped interface registers at all.
