<<<
:sectnums:
==== Instruction Cache (iCache)

[cols="<3,<3,<4"]
[grid="none"]
|=======================
| Hardware source files:  | neorv32_cache.vhd     | generic cache module
|                         | neorv32_cache_ram.vhd | tag and data RAM (primitive/IP wrapper)
| Software driver files:  | none                  |
| Top entity ports:       | none                  |
| Configuration generics: | `ICACHE_EN`           | implement CPU-exclusive instruction cache (I$) when `true`
|                         | `ICACHE_NUM_BLOCKS`   | number of cache blocks ("cache lines"); has to be a power of two
|                         | `CACHE_BLOCK_SIZE`    | size of a cache block in bytes (global configuration for I$ and D$); has to be a power of two, min 4
|                         | `CACHE_BURSTS_EN`     | enable burst transfers for cache update
| CPU interrupts:         | none                  |
|=======================

**Key Features**

* Direct-mapped read-only cache
* Configurable number of lines
* Configurable line size
* Allows bypassing for _uncached_ accesses
* Tag and data storage mapped to memory primitives


**Overview**

The processor features an optional CPU instruction cache. The cache is connected directly to the <<_cpu_front_end>>
fetch interface and provides full-transparent accesses. The cache is direct-mapped and read-only.
For the <<_dual_core_configuration>> each CPU core is equipped with a private instruction cache.

The instruction cache is enabled by the `ICACHE_EN` generic. The total cache memory size in bytes is defined by
`ICACHE_NUM_BLOCKS x CACHE_BLOCK_SIZE`. `ICACHE_NUM_BLOCKS` defines the number of cache blocks (or "cache lines")
and `CACHE_BLOCK_SIZE` defines the block size in bytes; note that the latter configuration is global for all caches.

.Burst Transfers
[IMPORTANT]
Cache update operations (to resolve a cache miss) can use <<_locked_bus_accesses_and_bursts,burst transfers>>
to increase performance. Burst operations are enabled (for all caches) by the `CACHE_BURSTS_EN` top generic.
When bursts are enabled all cache block transfers are **always executed as burst transfers**. Hence, all devices,
memories and endpoints that can be accessed by the cache must also be able to process bursts (including the
<<_processor_external_bus_interface_xbus>>).

.Uncached Accesses
[NOTE]
The cache provides direct/uncached accesses to memory (bypassing the cache) in order to access memory-mapped IO
(like the processor-internal IO/peripheral modules). All accesses that target the address range from `0xF0000000`
to `0xFFFFFFFF` will bypass the cache. See section <<_address_space>> for more information. Furthermore, atomic
memory operations  will always **bypass** the cache.

.Manual Cache Clear/Reload and Memory Coherence
[NOTE]
By executing the `fence.i` instruction the instruction cache is cleared and reloaded.
See section <<_memory_coherence>> for more information.

.Cache Block Update Bus Error Handling
[NOTE]
If the cache encounters a bus error while downloading a new block from main memory, the entire block is discarded
and an bus error exception is raised.

.Retrieve Cache Configuration by Software
[TIP]
Software can retrieve the cache configuration/layout from the <<_sysinfo_cache_configuration>> register.

.Memory Primitives
[TIP]
The cache's tag and data RAMs are encapsulated as individual wrapper (`neorv32_cache_ram.vhd`) that can be
replaced by a technology-specific IP. All interface ports provide static signal widths to ease replacement.
