<<<
<<<
:sectnums:
==== Processor-Internal Data Cache (dCACHE)

[cols="<3,<3,<4"]
[grid="none"]
|=======================
| Hardware source files:  | neorv32_cache.vhd   | Generic cache module
| Software driver files:  | none                |
| Top entity ports:       | none                |
| Configuration generics: | `DCACHE_EN`         | implement processor-internal data cache (D$) when `true`
|                         | `DCACHE_NUM_BLOCKS` | number of cache blocks ("cache lines"); has to be a power of two
|                         | `CACHE_BLOCK_SIZE`  | size of a cache block in bytes; has to be a power of two (global configuration for I$ and D$)
| CPU interrupts:         | none |
|=======================


**Overview**

The processor features an optional CPU data cache. The cache is connected directly to the CPU's data access interface
and provides full-transparent accesses. The cache is direct-mapped and uses "write-allocate" and "write-back" strategies.
In the <<_dual_core_configuration>> each CPU core is equipped with a private data cache.

The data cache is implemented if `DCACHE_EN` it _true_. The total cache memory size in bytes is defined by
`DCACHE_NUM_BLOCKS x CACHE_BLOCK_SIZE`. `DCACHE_NUM_BLOCKS` defines the number of cache blocks (or "cache lines")
and `CACHE_BLOCK_SIZE` defines the block size in bytes; note that this configuration is global for all caches.

.Retrieve Cache Configuration from Software
[TIP]
Software can retrieve the cache configuration/layout from the <<_sysinfo_cache_configuration>> register.

.Uncached Accesses
[NOTE]
The cache provides direct/uncached accesses to memory (bypassing the cache) in order to access memory-mapped IO (like the
processor-internal IO/peripheral modules). All accesses that target the address range from `0xF0000000` to `0xFFFFFFFF`
will bypass the cache. Hence, access will not be cached. See section <<_address_space>> for more information. Furthermore,
the atomic memory operations of the <<_zaamo_isa_extension>> will always **bypass** the cache.

.Manual Cache Flush/Clear/Reload and Memory Coherence
[NOTE]
By executing the `fence` instruction the data cache is flushed, cleared and reloaded.
See section <<_memory_coherence>> for more information.

.Cache Block Update Fault Handling
[NOTE]
If the cache encounters a bus error when uploading a modified block to main memory or when
downloading a new block from main memory, the entire block is invalidated and a bus access
error exception is raised.
