neorv32_package.vhd
neorv32_clockgate.vhd
neorv32_fifo.vhd
neorv32_cpu_decompressor.vhd
neorv32_cpu_control.vhd
neorv32_cpu_regfile.vhd
neorv32_cpu_cp_shifter.vhd
neorv32_cpu_cp_muldiv.vhd
neorv32_cpu_cp_bitmanip.vhd
neorv32_cpu_cp_fpu.vhd
neorv32_cpu_cp_cfu.vhd
neorv32_cpu_cp_cond.vhd
neorv32_cpu_alu.vhd
neorv32_cpu_lsu.vhd
neorv32_cpu_pmp.vhd
neorv32_cpu.vhd
neorv32_intercon.vhd
neorv32_cache.vhd
neorv32_dma.vhd
neorv32_imem.entity.vhd
neorv32_dmem.entity.vhd
neorv32_boot_rom.vhd
neorv32_xip.vhd
neorv32_xbus.vhd
neorv32_cfs.vhd
neorv32_sdi.vhd
neorv32_gpio.vhd
neorv32_wdt.vhd
neorv32_mtime.vhd
neorv32_uart.vhd
neorv32_spi.vhd
neorv32_twi.vhd
neorv32_pwm.vhd
neorv32_trng.vhd
neorv32_neoled.vhd
neorv32_xirq.vhd
neorv32_gptmr.vhd
neorv32_onewire.vhd
neorv32_slink.vhd
neorv32_crc.vhd
neorv32_sysinfo.vhd
neorv32_debug_dtm.vhd
neorv32_debug_dm.vhd
neorv32_top.vhd
neorv32_bootloader_image.vhd
neorv32_application_image.vhd
mem/neorv32_imem.default.vhd
mem/neorv32_dmem.default.vhd
