override APP_SRC = park_loop.S
override MARCH = rv32i_zicsr_zifencei
override LD_SCRIPT = ./debug_rom.ld

# Modify this variable to fit your NEORV32 setup (neorv32 home folder)
NEORV32_HOME ?= ../..
include $(NEORV32_HOME)/sw/common/common.mk
