<<<
:sectnums:
== Building the Documentation

The data sheet and user guide is written using `asciidoc`. The according source files
can be found in `docs`. The documentation of the software framework is written _in-code_ using `doxygen`.
A makefiles in the project's `docs` directory is provided to build all of the documentation as HTML pages
or as PDF documents.

.Pre-Built PDFs
[TIP]
Pre-rendered PDFs are available online as nightly pre-releases: https://github.com/stnolting/neorv32/releases/tag/nightly_release
The HTML-based documentation is also available online at the project's https://stnolting.github.io/neorv32/[GitHub Page].

The makefile provides a help target to show all available build options and their according outputs.

[source,bash]
----
neorv32/docs$ make help
----

.Example: Generate HTML documentation (data sheet) using `asciidoctor`
[source,bash]
----
neorv32/docs$ make html
----

.Using Containers for Building
[TIP]
If you don't have `asciidoctor` / `asciidoctor-pdf` installed, you can still generate all the documentation using
a _docker container_ via `make container`.
