<<<
:sectnums:
== Using the NEORV32 Bootloader

.Customization
[NOTE]
This section assumes the _default_ configuration of the NEORV32 bootloader.
See the NEORV32 data sheet's bootloader section for more information.


:sectnums:
=== Uploading an Executable

The bootloader provides an interactive serial terminal via UART that also allows to transfer
a pre-compiled executable for execution.

[start=1]
. Connect the primary UART (UART0) interface of the processor to a serial port of your host computer.
. Start a serial terminal program. For Windows I can highly recommend TeraTerm. For Linux systems you can use
for example `cutecom` (recommended) or `GTKTerm`.

.Terminal Requirements
[NOTE]
Any terminal program that can connect to a serial port should work. However, make sure the program
can transfer data in _raw_ byte mode without any protocol overhead around it. Some terminal programs struggle with
transmitting files larger than 4kB (see https://github.com/stnolting/neorv32/pull/215). Try a different program
if uploading a binary does not work.

[start=3]
. Open a connection to the the serial port your UART is connected to. The default NEORV32 bootloader uses the
following configuration:

* 19200 Baud
* 8 data bits
* 1 stop bit
* no parity bits
* no transmission/flow control protocol; just raw data

[start=4]
. Press the NEORV32 reset button to restart the bootloader. The status LED starts blinking and the
bootloader intro screen appears in the console. Press any key to abort the automatic boot sequence
and to start the actual bootloader user interface console.

.Bootloader console; aborted auto-boot sequence
[source,bash]
----
NEORV32 Bootloader

BLDV: Mar 30 2025
HWV:  0x01110202
CLK:  0x017d7840
MISA: 0x40801104
XISA: 0x00000083
SOC:  0x000f800d
IMEM: 0x00004000
DMEM: 0x00002000

Autoboot in 10s. Press any key to abort. <9>
Aborted.

Available CMDs:
 h: Help
 r: Restart
 u: Upload via UART
 s: Store to SPI flash
 l: Load from SPI flash
 e: Start executable
CMD:>
----

[start=5]
. Execute the "Upload" command by typing `u`. Now the bootloader is waiting for a binary executable to be send.

[source,bash]
----
CMD:> u
Awaiting neorv32_exe.bin...
----

[start=6]
. Use the "send file" option of your terminal program to send a valid NEORV32 executable (`neorv32_exe.bin`).
Make sure the terminal send the executable in raw binary mode.
. If everything went fine, OK will appear in your terminal:

[source,bash]
----
CMD:> u
Awaiting neorv32_exe.bin... OK
----

[start=8]
. The executable is now in the instruction memory of the processor. To execute the program right
now run the "Execute" command by typing `e`:

[source,bash]
----
CMD:> e
Booting...
----


:sectnums:
=== Programming an External SPI Flash via the Bootloader

The default processor-internal NEORV32 bootloader supports automatic booting from an external SPI flash.
This guide shows how to write an executable to the SPI flash via the bootloader so it can be automatically
fetched and executed after processor reset. For example, you can use a section of the FPGA bitstream
configuration memory to store an application executable.

[start=1]
. At first, reset the NEORV32 processor and wait until the bootloader start screen appears in your terminal program.
. Abort the auto boot sequence and start the user console by pressing any key.
. Press `u` to upload the executable that you want to store to the external flash:

[source]
----
CMD:> u
Awaiting neorv32_exe.bin...
----

[start=4]
. Send the binary in raw binary via your terminal program. When the upload is completed and "OK"
appears, press `s` to trigger the programming of the flash::

[source]
----
CMD:> u
Awaiting neorv32_exe.bin... OK
CMD:> s
Write 0x00001614 bytes to SPI flash @0x00400000 (y/n)?
----

[start=5]
. The bootloader shows the size of the executable and the base address of the SPI flash where the
executable will be stored. A prompt appears: type `y` to start the programming or type `n` to abort.

[source]
----
CMD:> u
Awaiting neorv32_exe.bin... OK
CMD:> s
Write 0x00001614 bytes to SPI flash @0x00400000 (y/n)?
Flashing... OK
CMD:>
----

[start=6]
. If "OK" appears in the terminal line, the programming process was successful. Now you can use the
auto boot sequence to automatically boot your application from the flash at system start-up without
any user interaction.


:sectnums:
=== Bootloader SPI Flash Requirements

The bootloader can access an SPI-compatible flash via the processor's top entity SPI port. By default, the flash
chip-select line is driven by `spi_csn_o(0)` and the SPI clock uses 1/8 of the processor's main clock as clock frequency.
The SPI flash has to support single-byte read and write operations, 24-bit addresses and at least the following standard commands:

* `0x02`: Program page (write byte)
* `0x03`: Read data (byte)
* `0x04`: Write disable (for volatile status register)
* `0x05`: Read (first) status register
* `0x06`: Write enable (for volatile status register)
* `0xAB`: Wake-up from sleep mode (optional)
* `0xD8`: Block erase (64kB)

.SPI Flash Power Down Mode
[NOTE]
The bootloader will issue a "wake-up" command prior to using the SPI flash to ensure it is not
in sleep mode / power-down mode (see https://github.com/stnolting/neorv32/pull/552).
