name: Windows

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:


  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:

    - name: '🧰 Repository Checkout'
      uses: actions/checkout@v2

    - name: '🔧 Generate examples matrix'
      id: generate
      run: ./.github/generate-job-matrix.py


  Implementation:
    needs: Matrix
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.Matrix.outputs.matrix) }}
    name: '🟦 MINGW64 | ${{ matrix.board }} · ${{ matrix.design }}'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🟦 Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          make
          mingw-w64-x86_64-yosys
          mingw-w64-x86_64-nextpnr
          mingw-w64-x86_64-icestorm
          mingw-w64-x86_64-prjtrellis
          mingw-w64-x86_64-python-pip

    - name: '⚙️ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        # The command 'git describe' (used for version) needs the history.
        fetch-depth: 0

    - name: '🐍 Install doit'
      run: pip install doit

    - name: '🚧 Generate ${{ matrix.board }} ${{ matrix.design }} bitstream'
      run: doit ex:${{ matrix.board }} -d ${{ matrix.design }} clean bit


  Processor:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          {icon: '⬛', installs: 'MINGW32', arch: i686,   pkg: 'mcode' },
          {icon: '🟦', installs: 'MINGW64', arch: x86_64, pkg: 'llvm'  },
        ]
    name: '${{ matrix.icon }} ${{ matrix.installs }} | VUnit'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '⚙️ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2
      with:
        # The command 'git describe' (used for version) needs the history.
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.installs }}
        update: true
        install: >
          make
          mingw-w64-${{ matrix.arch }}-ghdl-${{ matrix.pkg }}
          mingw-w64-${{ matrix.arch }}-python-pip
          mingw-w64-${{ matrix.arch }}-riscv64-unknown-elf-gcc

    - name: '⚙️ Build and install Processor Check software'
      run: |
        make -C sw/example/processor_check \
          RISCV_PREFIX=riscv64-unknown-elf- \
          clean_all \
          USER_FLAGS+=-DRUN_CHECK \
          USER_FLAGS+=-DUART0_SIM_MODE \
          USER_FLAGS+=-DSUPPRESS_OPTIONAL_UART_PRINT \
          MARCH=-march=rv32imac \
          info \
          all

    - name: '🐍 Install VUnit'
      run: pip install vunit_hdl

    - name: '🚧 Run Processor Hardware Tests with VUnit'
      run: ./sim/run.py --ci-mode -v
