name: Windows

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:


  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:

    - name: '🧰 Repository Checkout'
      uses: actions/checkout@v2

    - name: '🐍 Install doit'
      run: pip install doit

    - name: '🔧 Generate examples matrix'
      id: generate
      run: doit GenerateExamplesJobMatrix


  Implementation:
    needs: Matrix
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.Matrix.outputs.matrix) }}
    name: '🟦 MINGW64 | ${{ matrix.board }} · ${{ matrix.design }}'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🟦 Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          make
          mingw-w64-x86_64-yosys
          mingw-w64-x86_64-nextpnr
          mingw-w64-x86_64-icestorm
          mingw-w64-x86_64-prjtrellis
          mingw-w64-x86_64-python-pip

    - name: '⚙️ git config'
      run: git config --global core.autocrlf input
      shell: bash

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '🐍 Install doit'
      run: pip install doit

    - name: '🚧 Generate ${{ matrix.board }} ${{ matrix.design }} bitstream'
      run: doit ex:${{ matrix.board }} -d ${{ matrix.design }} clean bit


  Processor:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          {icon: '⬛', installs: 'MINGW32', arch: i686,   pkg: 'mcode' },
          {icon: '🟦', installs: 'MINGW64', arch: x86_64, pkg: 'llvm'  },
        ]
    name: '${{ matrix.icon }} ${{ matrix.installs }} | VUnit'
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.installs }}
        update: true
        install: >
          make
          mingw-w64-${{ matrix.arch }}-ghdl-${{ matrix.pkg }}
          mingw-w64-${{ matrix.arch }}-python-pip
          mingw-w64-${{ matrix.arch }}-riscv64-unknown-elf-gcc

    - name: '🐍 Install doit and VUnit'
      run: pip install doit vunit_hdl

    - name: '⚙️ Build and install Processor Check software'
      run: doit BuildAndInstallCheckSoftware
      env:
        RISCV_PREFIX: riscv64-unknown-elf-

    - name: '🚧 Run Processor Hardware Tests with VUnit'
      run: doit sim:VUnit -a '--ci-mode -v'
